apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: production
spec:
  nodeSelector:
    nodeType: Proxies
    demo: graphy
  tolerations:
    - key: app
      operator: Equal
      value: blue
      effect: NoExecute
  securityContext:
    runAsUser: 1000
  containers:
      - command:
          - ""
        name: nginx
        image: nginx
        ports:
            - containerPort: 8080
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
              - "MAC_ADMIN"
