apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: production
spec:
    securityContext:
      runAsUser: 1000
    containers:
        - command:
            - ""
          name: nginx
          image: nginx
          ports:
              - containerPort: 8080
          securityContext:
            runAsUser: 1000
            capabilities:
              add:
                - "MAC_ADMIN"
