apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /web
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    run: fileserver
spec:
  containers:
    - name: fileserver
      image: kodekloud/fileserver
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /web
          name: data-store
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
  labels:
    type: gop
spec:
  selector:
    run: fileserver
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31200