apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    #targetport: port point to container itself
    - targetPort: 80
    #port: port pointing to service
      port: 80
    #nodePort: port pointing to node
      nodePort: 30008
  selector:
    app: myapp
    type: front-end