apiVersion: v1
kind: Pod
metadata:
  name: pod-security-context
  labels:
    type: experimental
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command:
        - sleep
        - infinity
      securityContext:
        runAsUser: 0
        capabilities:
          add:
            - MAC_ADMIN