apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: ubuntu
      volumeMounts:
        - name: foo
          mountPath: "/etc/secret-tmp"
          readOnly: true
      command:
        - '/bin/sleep'
        - '365d'
      env:
        - name: TESTARAZO
          valueFrom:
            secretKeyRef:
              key: another
              name: secret-tmp
  volumes:
    - name: foo
      secret:
        secretName: secret-tmp